<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZqRnxC1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZqRnxC1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZqRnxC1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZqRnxC1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZqRnxC1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZqRnxC1',
    'container.build_id' => 'f68f1bce',
    'container.build_time' => 1541171156,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZqRnxC1');
