<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTQUU1A4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTQUU1A4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTQUU1A4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTQUU1A4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTQUU1A4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TQUU1A4',
    'container.build_id' => '32b2fbe6',
    'container.build_time' => 1540393787,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTQUU1A4');
